#!/bin/bash

docker build -t paranuara .
mongoimport --db paranuara --collection companies --drop --jsonArray --file ./resources/companies.json
mongoimport --db paranuara --collection people --drop --jsonArray --file ./resources/people.json
mongoimport --db paranuara --collection food_classes --drop --jsonArray --file ./resources/food_classes.json