#!/bin/bash

if [ "${OSTYPE//[0-9.]/}" = 'darwin' ]; then
  docker run --env MONGODB_HOST='docker.for.mac.localhost' -p 7777:7777 --rm -ti -v `pwd`:/usr/src/app paranuara
else
  docker run --env MONGODB_HOST='localhost' --network=host --rm -ti -v `pwd`:/usr/src/app paranuara
fi
